### ISSUE TITLE
[Bug]: error cndy.state.goLiveDate.toNumber 

### ISSUE THREAD

**Issue by uraxlizard** [metaplex-foundation/candy-machine-ui#2]
### Feature

The problem is when you do yarn install, then set your .env file and do  yarn start the mint button appears but it is not clickable and in console the following message appears:

TypeError: cndy.state.goLiveDate.toNumber is not a function

### Ideal solution or implementation

Fix the issue related to latest release of candy-machine-ui

**Comment by Sonicfury** [comment]
I made the modification suggested in #3 and it worked for me. Thanks MarkSackerberg 🎉

For those who don't want to wait until the PR is merged:
in `src/candy-machine.ts`, just go l. 210 and change `goLiveDate` by `goLiveDate: state.goLiveDate`

**Comment by Drnomoney** [comment]
> 
![Screen Shot 2022-07-18 at 20 39 29](https://user-images.githubusercontent.com/97303424/179603717-04fbeed8-7306-4d94-9557-6371c1008bfb.png)


I did that - it worked at least now i can see how many nft still -- and i can see the price too -- 
but I got a new err  !!
i have enough sol - and i can mint using the terminal -- but the mint button still clickable ---

**Comment by sindrisigfus** [comment]
> > 
> 
> ![Screen Shot 2022-07-18 at 20 39 29](https://user-images.githubusercontent.com/97303424/179603717-04fbeed8-7306-4d94-9557-6371c1008bfb.png)
> 
> I did that - it worked at least now i can see how many nft still -- and i can see the price too -- ![Screen Shot 2022-07-18 at 20 58 52](https://user-images.githubusercontent.com/97303424/179606744-6e0ba8cf-63d7-49c5-bc51-752e4af916cb.png)
> 
> but I got a new err !! i have enough sol - and i can mint using the terminal -- but the mint button still clickable ---

Works if you do this.
goLiveDate: state.data.goLiveDate,

**Comment by Drnomoney** [comment]
Thank you Very much it works !!!
